routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/backend_zone', function(){
    return view('admin.dashboard');
})->middleware(['auth', 'auth.superadmin']);

Route::namespace('Admin')->prefix('backend_zone')->middleware(['auth', 'auth.superadmin'])->name('backend_zone.')->group(function(){
    Route::resource('/users', 'UserController', ['except' => ['show', 'create', 'store']]);
});

Route::namespace('User')->prefix('member_zone')->middleware(['auth', 'auth.member'])->name('member_zone.')->group(function(){
    Route::resource('/profile', 'UserController', ['except' => ['show', 'create', 'store']]);
});

// Route::get('/admin_zone/announcement', function(){
//     return view('admin.announcement');
// });

// Route::get('/admin_zone/member', function(){
//     return view('admin.member');
// });

// Route::get('/admin_zone/staff', function(){
//     return view('admin.staff');
// });

// Route::get('/admin_zone/deposit', function(){
//     return view('admin.deposit');
// });

// Route::get('/admin_zone/withdraw', function(){
//     return view('admin.withdraw');
// });

// Route::get('/admin_zone/bank', function(){
//     return view('admin.bank');
// });

// Route::get('/admin_zone/mutation', function(){
//     return view('admin.mutation');
// });

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function users()
    {
        return $this->belongsToMany('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }

    public function hasAnyRoles($roles)
    {
        return null !== $this->roles()->whereIn('name', $roles)->first();
    }

    public function hasAnyRole($role)
    {
        return null !== $this->roles()->where('name', $role)->first();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.index')->with('users', User::all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.index')->with('users', User::where('name', Auth::user()->name));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/announcement.blade.php
@extends('layouts.master')

@section('breadcrumb')
Announcement
@endsection

@section('content')
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Striped Table</h4>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Time</th>
                            <th>Content</th>
                            <th>Create By</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1.</td>
                            <td>25 February 2020</td>
                            <td width="500px">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est, doloremque? Aut, et repudiandae. Beatae accusamus impedit delectus reprehenderit fugit quasi, incidunt aperiam nisi accusantium ullam nulla exercitationem ipsam qui! Porro veniam quos, saepe consequuntur soluta, praesentium, suscipit tempora necessitatibus eveniet voluptatem reiciendis molestias corrupti quas quibusdam ab blanditiis fugiat tenetur?</td>
                            <td>Polandia</td>
                            <td>
                                <input type="checkbox" checked data-toggle="toggle" data-onstyle="success" data-offstyle="outline-light">
                            </td>
                        </tr>
                        <tr>
                            <td>2.</td>
                            <td>29 February 2020</td>
                            <td width="500px">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error quae quibusdam ipsum nesciunt repudiandae sit iste veritatis. Fuga similique hic quia voluptas iure ipsa aliquam illum nesciunt, consectetur corrupti blanditiis sit quibusdam inventore quidem dolores quo doloribus, officiis provident nemo. Omnis illo ratione totam, tempora enim, modi, quas suscipit ad sapiente eum quo possimus saepe! Ducimus voluptatum sit fugit. Quaerat explicabo, dolorem beatae accusamus unde, non doloremque sint fugiat ducimus dolorum at culpa. Sit fugit ut nisi nobis itaque vel iusto aspernatur iste, enim deleniti vero. Tempora tenetur molestiae fugit quasi minus optio doloribus vel voluptatibus voluptate similique, deserunt inventore.</td>
                            <td>Polandia</td>
                            <td>
                                <input type="checkbox" checked data-toggle="toggle" data-onstyle="success" data-offstyle="outline-light">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/bank.blade.php
@extends('layouts.master')

@section('breadcrumb')
Manage Bank Account
@endsection

@section('content')
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Bank Name</th>
                                <th class="text-center">Account Holder</th>
                                <th class="text-center">Account Number</th>
                                <th class="text-left" width="230">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1.</td>
                                <td class="text-left">BCA</td>
                                <td class="text-left">AQUA</td>
                                <td class="text-left">1120039292</td>
                                <td>
                                <i class="fa fa-circle text-success"></i> Online
                                    <div class="dropdown float-right">
                                        <button class="btn btn-inverse-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            action
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                            <button class="dropdown-item" type="button">Action</button>
                                            <button class="dropdown-item" type="button">Another action</button>
                                            <button class="dropdown-item" type="button">Something else here</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>2.</td>
                                <td class="text-left">BNI</td>
                                <td class="text-left">AQUA</td>
                                <td class="text-left">0024339218</td>
                                <td>
                                <i class="fa fa-circle text-success"></i> Online
                                    <div class="dropdown float-right">
                                        <button class="btn btn-inverse-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            action
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                            <button class="dropdown-item" type="button">Action</button>
                                            <button class="dropdown-item" type="button">Another action</button>
                                            <button class="dropdown-item" type="button">Something else here</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>3.</td>
                                <td class="text-left">BRI</td>
                                <td class="text-left">AQUA</td>
                                <td class="text-left">54521109239292</td>
                                <td>
                                <i class="fa fa-circle text-success"></i> Online
                                    <div class="dropdown float-right">
                                        <button class="btn btn-inverse-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            action
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                            <button class="dropdown-item" type="button">Action</button>
                                            <button class="dropdown-item" type="button">Another action</button>
                                            <button class="dropdown-item" type="button">Something else here</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.master')

@section('breadcrumb')
Dashboard
@endsection

@section('content')
<!-- Deposit -->
<div class="col-md-4 grid-margin">
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h4 style="font-size: 20px;" class="card-title"><strong><i class="ti-angle-double-right text-primary"></i>&nbsp;&nbsp;Deposit Request</h4></strong>
            </div><hr>
            <!-- <p class="card-description">David Beckham</p> -->
            <div class="list d-flex align-items-center border-bottom py-3">
                <i class="fa fa-circle text-success"></i>
                <div class="wrapper w-100 ml-3">
                    <b>J. Zanneti</b>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <p class="mb-0">Amount: Rp. 450,000</p>
                        </div>
                        <small class="text-muted ml-auto">2 hours ago</small>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <p class="text-muted">Sender</p>
                <h4 style="margin-top: -15px;">J. Zanneti</h4>
                <p style="margin-top: -6px;">BCA / 234-234-2345</p>
                <hr>
                <p class="text-muted">Receiver</p>
                <h4 style="margin-top: -15px;">Aqua</h4>
                <p style="margin-top: -6px;">BCA / 456-456-4567</p>
                <div class="d-flex justify-content-between">
                    <a href="#" class="btn btn-inverse-danger"><i class="fa fa-times"></i> Reject</a>
                    <a href="#" class="btn btn-inverse-success"><i class="fa fa-check"></i> Accept</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Withdraw -->
<div class="col-md-4 grid-margin">
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h4 style="font-size: 20px;" class="card-title"><strong><i class="ti-angle-double-up text-warning"></i>&nbsp;&nbsp;Withdraw Request</h4></strong>
            </div><hr>
            <!-- <p class="card-description">David Beckham</p> -->
            <div class="list d-flex align-items-center border-bottom py-3">
                <i class="fa fa-circle text-warning"></i>
                <div class="wrapper w-100 ml-3">
                    <b>Diego Milito</b>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <p class="mb-0">Amount: Rp. 350,000</p>
                        </div>
                        <small class="text-muted ml-auto">10 minutes ago</small>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <p class="text-muted">Receiver</p>
                <h4 style="margin-top: -15px;">Diego Milito</h4>
                <p style="margin-top: -6px;">BCA / 987-987-9876</p>
                <div class="d-flex justify-content-between">
                    <a href="#" class="btn btn-inverse-danger">Cancel <i class="fa fa-times"></i></a>
                    <a href="#" class="btn btn-inverse-success">Accept <i class="fa fa-check"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Lock Member -->
<div class="col-md-4 grid-margin">
    <a href="#" style="text-decoration: none;">
    <div class="card">
        <div class="card-body">
            <h4 style="font-size: 20px;" class="card-title"><strong><i class="fa fa-lock text-danger"></i>&nbsp;&nbsp;Lock Member Site</h4></strong>
        </div>
    </a>
    </div>

    <br>

    <a href="#" style="text-decoration: none;">
    <div class="card">
        <div class="card-body">
            <h4 style="font-size: 20px;" class="card-title"><strong><i class="fa fa-users text-primary"></i>&nbsp;&nbsp;Online Members (235)</h4></strong>
        </div>
    </a>
    </div>

    <br>

    <!-- Banks -->
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h4 style="font-size: 20px;" class="card-title"><strong><i class="icon-wallet text-success"></i>&nbsp;&nbsp;Bank Account</h4></strong>
            </div><hr>
            <!-- <p class="card-description">David Beckham</p> -->
            <div class="list d-flex align-items-center border-bottom py-3">
                <i style="font-size: 8px;" class="fa fa-circle fa-1x text-success"></i>
                <div class="wrapper w-100 ml-3">
                    <b>BCA</b>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <p class="mb-0">AQUA: 456-456-4567</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="list d-flex align-items-center border-bottom py-3">
                <i style="font-size: 8px;" class="fa fa-circle fa-1x text-success"></i>
                <div class="wrapper w-100 ml-3">
                    <b>BNI</b>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <p class="mb-0">GALON: 6345-645-623</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="list d-flex align-items-center border-bottom py-3">
                <i style="font-size: 8px;" class="fa fa-circle fa-1x text-success"></i>
                <div class="wrapper w-100 ml-3">
                    <b>BRI</b>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <p class="mb-0">HABIS: 456-456-456-764-524</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/deposit.blade.php
@extends('layouts.master')

@section('breadcrumb')
Deposit Request
@endsection

@section('content')
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Username</th>
                                <th class="text-center">From</th>
                                <th class="text-center">To</th>
                                <th class="text-center">Amount</th>
                                <th class="text-center">When</th>
                                <th class="text-center">Processed By</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1.</td>
                                <td class="text-left">mid0ne</td>
                                <td class="text-left">BCA / 7838788373</td>
                                <td class="text-left">BCA / 1130029432</td>
                                <td class="text-left">300.000</td>
                                <td class="text-right">2020-02-12 00:12:02</td>
                                <td class="text-right">admin1</td>
                                <td class="text-center">
                                    <button class="btn btn-sm btn-inverse-secondary">Mistake</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Manage Users</div>

                <div class="card-body">
                    <table class="table table-hover">
                        <thead class="text-success">
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Roles</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/mutation.blade.php
@extends('layouts.master')

@section('breadcrumb')
Account Mutation
@endsection

@section('content')

@endsection

resources/views/admin/withdraw.blade.php
@extends('layouts.master')

@section('breadcrumb')
Withdraw Request
@endsection

@section('content')
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Username</th>
                                <th class="text-center">Bank Name</th>
                                <th class="text-center">Account Number</th>
                                <th class="text-center">Account Holder</th>
                                <th class="text-center">Amount</th>
                                <th class="text-center">When</th>
                                <th class="text-center">Processed By</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1.</td>
                                <td class="text-left">mid0ne</td>
                                <td class="text-left">BCA</td>
                                <td class="text-left">7838788373</td>
                                <td class="text-left">Midone</td>
                                <td class="text-right">200.000</td>
                                <td class="text-right">2020-12-02 00:12:02</td>
                                <td class="text-right">admin1</td>
                                <td class="text-center">
                                    <button class="btn btn-sm btn-inverse-secondary">Mistake</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="{{ route('backend_zone.users.index') }}">Manage Users</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/users/inde.blade.php
<h1>Member Page</h1>